[package]
name = "strategy-sample-rust"
version = "0.1.0"
authors = ["Eric C Huang <eric_c_huang@trendmicro.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstest = "0.6.4"
